version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  reviewers:
  - barriosnahuel
  ignore:
  - dependency-name: com.facebook.flipper:flipper
    versions:
    - 0.81.0
    - 0.82.0
    - 0.82.1
    - 0.82.2
    - 0.83.0
    - 0.85.0
  - dependency-name: com.google.firebase:firebase-bom
    versions:
    - 26.8.0
  - dependency-name: com.google.firebase:perf-plugin
    versions:
    - 1.3.5
  - dependency-name: com.google.truth:truth
    versions:
    - 1.1.2
  - dependency-name: org.robolectric:robolectric
    versions:
    - "4.5"
  - dependency-name: io.mockk:mockk
    versions:
    - 1.10.5
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk8
    versions:
    - 1.4.21-2
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.21-2
