version: 2.1
orbs:
  android: circleci/android@0.2.0
#  codecov: codecov/codecov@1.0.5
jobs:
  "test":
    executor: android/android
    steps:
      - checkout
      - run:
          name: "Run Tests"
          command: ./gradlew test
#      - codecov/upload:
#          file: "app/build/jacoco/testDebugUnitTest.exec"
#      - codecov/upload:
#          file: "app/build/jacoco/testReleaseUnitTest.exec"
  "code-analysis":
    executor: android/android
    steps:
      - checkout
      - run:
          name: "Run Code Analyzers"
          command: ./gradlew check -x test
      - run:
          name: "Run Vital Release Checks"
          command: ./gradlew app:lintVitalRelease
  "build":
    executor: android/android
    steps:
      - checkout
      - run:
          name: "Run App Build"
          command: ./gradlew app:build -x check -x lintVitalRelease
workflows:
  version: 2.1
  "Pull Requests Workflow":
    jobs:
      - test
      - code-analysis
      - build