version: 2.1
orbs:
  android: circleci/android@0.2.0
jobs:
  "test":
    executor: android/android
    steps:
      - checkout
      - run:
          name: "Run Tests"
          command: ./gradlew test
      - store_artifacts:
          path: "app/build/reports/tests/"
  "code-analysis":
    executor: android/android
    steps:
      - checkout
      - run:
          name: "Run Code Analyzers"
          command: ./gradlew check -x test
      - run:
          name: "Run Vital Release Checks"
          command: ./gradlew app:lintVitalRelease
      - store_artifacts:
          path: "app/build/reports/checkstyle/"
      - store_artifacts:
          path: "app/build/reports/pmd/"
      - store_artifacts:
          path: "app/build/reports/lint-results.html"
      - store_artifacts:
          path: "app/build/reports/detekt/detekt.html"
  "build":
    executor: android/android
    steps:
      - checkout
      - run:
          name: "Run App Build"
          command: ./gradlew app:build -x check -x lintVitalRelease -x uploadCrashlyticsMappingFileRelease
      - run:
          name: "Run App Bundle"
          command: ./gradlew app:bundle -x uploadCrashlyticsMappingFileRelease
workflows:
  version: 2.1
  "Pull Requests Workflow":
    jobs:
      - test
      - code-analysis
      - build